language: go
go:
  - 1.12.x
  - 1.11.x
sudo: true
env:
  - GO111MODULE=on
install:
  - sudo apt-get -y install libpcap-dev
script:
  #go test generator_test.go
  #go test dialer_test.go
  #go test connect_test.go
  #go test interface_test.go
  sudo go test -test.run ^TestSynScanner$
  sudo go test -test.run ^TestSynScanner_simple$
  sudo go test -test.run ^TestSynScanner_Stop$