language: go
go:
  - 1.12.x
  - 1.11.x
sudo: true
env:
  - GO111MODULE=on
before_install:
  - sudo apt-get -y install libpcap-dev
script:
  - chmod +x .linux-test-su.sh
  - sudo ./.linux-test-su.sh $GOPATH `which go`